[tool.poetry]
name = "vscode-python-24307"
version = "0.1.0"
description = "Test repo to illustrate vscode-python issue 24307"
authors = ["Neil Fenwick <neil.fenwick@gmail.com>"]
license = "MIT"
readme = "README.md"

